modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "jcraftpolished"
version = "${version}"
displayName = "JCraft: Polished"
authors = "Arsik"
description = '''
This simple mod adds slab, stair, wall and pressure plate variants to the Meteorite blocks from JCraft: Eyes Of Ender
'''
logoFile = "assets/jcraftpolished/icon.png"

[[dependencies.jcraftpolished]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jcraftpolished]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jcraftpolished]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jcraftpolished]]
modId = "jcraft"
mandatory = true
versionRange = "[0.18.0,)"
ordering = "AFTER"
side = "BOTH"
